This one is a matrix problem: let's use NumPy!

# Sample input part 1 

Let's start with the sample.

In [1]:
sample = """1, 1
1, 6
8, 3
3, 4
5, 5
8, 9"""

In [2]:
sources = [tuple(map(int, line.split(', '))) for line in sample.split('\n')]

In [3]:
sources

[(1, 1), (1, 6), (8, 3), (3, 4), (5, 5), (8, 9)]

Let's write a function that returns a numpy grid of closest distances given a source and a grid size.

In [4]:
import numpy as np

def manhattan(source, grid_size):
    n, m = grid_size
    grid = np.empty(grid_size, dtype=int)
    X, Y = np.meshgrid(np.arange(n), np.arange(m))
    return np.abs(X - source[0]) + np.abs(Y - source[1])

In [5]:
manhattan(sources[0], (10, 10))

array([[ 2,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 4,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 5,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 6,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 7,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 8,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 9,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [6]:
manhattan(sources[1], (10, 10))

array([[ 7,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 4,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [7]:
a = manhattan(sources[0], (10, 10))
b = manhattan(sources[1], (10, 10))
np.where(a < b, np.ones_like(a), np.ones_like(a) * 2) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [8]:
grid_size = (10, 10)
nearest = np.ones(grid_size) * -1
min_dist = np.ones(grid_size, dtype=int) * 10000
for index, source in enumerate(sources):
    dist = manhattan(source, grid_size)
    nearest[dist == min_dist] = np.nan
    nearest = np.where(dist < min_dist, np.zeros_like(nearest) + index, nearest)
    min_dist = np.where(dist < min_dist, dist, min_dist)

In [9]:
nearest

array([[  0.,   0.,   0.,   0.,   0.,  nan,   2.,   2.,   2.,   2.],
       [  0.,   0.,   0.,   0.,   0.,  nan,   2.,   2.,   2.,   2.],
       [  0.,   0.,   0.,   3.,   3.,   4.,   2.,   2.,   2.,   2.],
       [  0.,   0.,   3.,   3.,   3.,   4.,   2.,   2.,   2.,   2.],
       [ nan,  nan,   3.,   3.,   3.,   4.,   4.,   2.,   2.,   2.],
       [  1.,   1.,  nan,   3.,   4.,   4.,   4.,   4.,   2.,   2.],
       [  1.,   1.,   1.,  nan,   4.,   4.,   4.,   4.,  nan,  nan],
       [  1.,   1.,   1.,  nan,   4.,   4.,   4.,   5.,   5.,   5.],
       [  1.,   1.,   1.,  nan,   4.,   4.,   5.,   5.,   5.,   5.],
       [  1.,   1.,   1.,  nan,   5.,   5.,   5.,   5.,   5.,   5.]])

If we set the infinite groups to zero that would be the 0, 2, 1 and 5 we would get:

In [10]:
infinites = [0, 2, 1, 5]
for infinite in infinites:
    nearest[nearest == infinite] = np.nan

In [11]:
for i in (set(range(len(sources))) - set(infinites)):
    print(i, np.nansum(nearest == i))

3 9
4 17


# Part 1 for real 

In [12]:
sources = [tuple(map(int, line.split(', '))) for line in open('input06.txt').readlines()]

In [13]:
np.array(sources).min(axis=0)

array([47, 43])

In [14]:
np.array(sources).max(axis=0)

array([355, 349])

In [15]:
grid_size = (360, 360)
nearest = np.ones(grid_size) * -1
min_dist = np.ones(grid_size, dtype=int) * 10000
for index, source in enumerate(sources):
    dist = manhattan(source, grid_size)
    nearest[dist == min_dist] = np.nan
    nearest = np.where(dist < min_dist, np.zeros_like(nearest) + index, nearest)
    min_dist = np.where(dist < min_dist, dist, min_dist)

In [16]:
nearest

array([[  0.,   0.,   0., ...,  28.,  28.,  28.],
       [  0.,   0.,   0., ...,  28.,  28.,  28.],
       [  0.,   0.,   0., ...,  28.,  28.,  28.],
       ..., 
       [  9.,   9.,   9., ...,  37.,  37.,  37.],
       [  9.,   9.,   9., ...,  37.,  37.,  37.],
       [  9.,   9.,   9., ...,  37.,  37.,  37.]])

The funny thing here is that this view of the matrix directly allows us to set the four corners as the infinites since it's the nearest neighbor to each corner that will be the infinite one!

In [17]:
infinites = [0, 9, 28, 37]
for infinite in infinites:
    nearest[nearest == infinite] = np.nan

In [18]:
for i in (set(range(len(sources))) - set(infinites)):
    print(i, np.nansum(nearest == i))

1 1086
2 2705
3 2730
4 1780
5 871
6 3873
7 2996
8 2303
10 1015
11 2972
12 3982
13 2310
14 4114
15 3428
16 2392
17 1759
18 4732
19 4491
20 2214
21 527
22 3879
23 735
24 1352
25 1627
26 813
27 1756
29 946
30 3532
31 3117
32 729
33 2662
34 2296
35 5187
36 318
38 1062
39 2902
40 3255
41 1632
42 120
43 2931
44 1494
45 2636
46 1437
47 356
48 4050
49 4493


In [19]:
max(np.nansum(nearest == i) for i in (set(range(len(sources))) - set(infinites)))

5187

# Part 2 sample 

In [20]:
sources = [tuple(map(int, line.split(', '))) for line in sample.split('\n')]

In [21]:
X, Y = np.meshgrid(np.arange(10), np.arange(10))

In [22]:
total = np.zeros((10, 10))
for source in sources:
    total += np.abs(X - source[0]) + np.abs(Y - source[1])

In [23]:
np.where(total < 32, 1, 0)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
np.sum(np.where(total < 32, 1, 0))

16

# Part 2 for real 

In [25]:
sources = [tuple(map(int, line.split(', '))) for line in open('input06.txt').readlines()]

In [26]:
grid_size = (360, 360)

In [27]:
X, Y = np.meshgrid(np.arange(360), np.arange(360))

In [28]:
total = np.zeros(grid_size)
for source in sources:
    total += np.abs(X - source[0]) + np.abs(Y - source[1])

In [29]:
np.sum(np.where(total < 10000, 1, 0))

34829